"""confirmed feature added

Revision ID: 087be5e66402
Revises: d26c45eccb81
Create Date: 2020-08-09 19:32:12.733686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087be5e66402'
down_revision = 'd26c45eccb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
