"""empty message

Revision ID: 3de2b212cff7
Revises: f056712640ab
Create Date: 2020-08-16 17:06:54.246355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3de2b212cff7'
down_revision = 'f056712640ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_image', sa.String(length=100), nullable=True))
    op.drop_column('user', 'd_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('d_image', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'display_image')
    # ### end Alembic commands ###
